@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.electrisoma.bloodisfuel.registry;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;